version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "songsApiIHeart"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ixz61t091w48"
s3_prefix = "songsApiIHeart"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
